{"name": "test_ResourceVault", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Zamit | Preparing for Success in the 21st Century' in 'Zamit | Login'", "trace": "self = <testCases.test_login_page.TestZamit object at 0x000001F6F1681E70>\n\n    def test_ResourceVault(self):\n        self.driver.find_element(By.XPATH,\"//a[contains(text(),'Resource Vault')]\").click()\n        time.sleep(2)\n        Marcketplace= self.driver.title\n>       assert Marcketplace in \"Zamit | Login\"\nE       AssertionError: assert 'Zamit | Preparing for Success in the 21st Century' in 'Zamit | Login'\n\ntestCases\\test_login_page.py:237: AssertionError"}, "start": 1680239601813, "stop": 1680239604013, "uuid": "82189b54-69ef-4023-899a-0ca186dd10d0", "historyId": "7e65e859e4168f29a01d7962c5794d1b", "testCaseId": "58fa0e0617afed34dd75c63579d46cd0", "fullName": "testCases.test_login_page.TestZamit#test_ResourceVault", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login_page"}, {"name": "subSuite", "value": "TestZamit"}, {"name": "host", "value": "M061"}, {"name": "thread", "value": "1764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login_page"}]}