{"name": "test_ResourceVault", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Zamit | Preparing for Success in the 21st Century' in 'Zamit | Login'", "trace": "self = <testCases.test_zamit_hp_Items.Test_Dashboard1 object at 0x000002196EA05D50>\n\n    def test_ResourceVault(self):\n        self.driver.find_element(By.XPATH, \"//a[contains(text(),'Resource Vault')]\").click()\n        time.sleep(2)\n        Marcketplace = self.driver.title\n>       assert Marcketplace in \"Zamit | Login\"\nE       AssertionError: assert 'Zamit | Preparing for Success in the 21st Century' in 'Zamit | Login'\n\ntest_zamit_hp_Items.py:256: AssertionError"}, "start": 1680188824694, "stop": 1680188827073, "uuid": "6b5a6c4f-6732-4241-af77-c8c3a0dcfdec", "historyId": "70b5e393916391133216da6d76864fb5", "testCaseId": "358889c4743fc44307b320e7108ab5c1", "fullName": "test_zamit_hp_Items.Test_Dashboard1#test_ResourceVault", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_zamit_hp_Items"}, {"name": "subSuite", "value": "Test_Dashboard1"}, {"name": "host", "value": "M061"}, {"name": "thread", "value": "33392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_zamit_hp_Items"}]}